language: php

php:
  - 7.0.30

sudo: required

services:
  - docker

before_install:
  - docker-compose pull
  - docker pull wordpress:cli

install:
  - git clone https://github.com/simevo/spid-wordpress
  - docker --version
  - docker-compose --version
  - docker-compose up --build --no-start
  - docker-compose start
  - docker ps
  - make post

script:
  - make test
