version: "3.3"

services:
  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "wp"
      MYSQL_USER: "wp"
      MYSQL_PASSWORD: "wp"
    networks:
      - "back"

  wp:
    env_file:
      - .env
    image: "wordpress:${WP_VERSION}"
    depends_on:
       - db
    ports:
      - "8099:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: "wp"
      WORDPRESS_DB_USER: "wp"
      WORDPRESS_DB_PASSWORD: "wp"
    volumes:
      - "./sp_conf:/var/www/html/spid-conf:rw"
      - "./spid-wordpress:/var/www/html/wp-content/plugins/spid-wordpress:ro"
    networks:
      - "front"
      - "back"

  idp:
    image: italia/spid-testenv2
    ports:
      - 8088:8088
    restart: always
    volumes:
      - type: bind
        source: ./idp_conf
        target: /app/conf
    networks:
      - "idp"

volumes:
  dbdata: {}

networks:
  front: {}
  back: {}
  idp: {}
